# Generated by Django 2.0.5 on 2018-06-26 00:22

from django.db import migrations, models
import pics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text_body', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to=pics.models.Post.picture_path)),
                ('pub_date', models.DateTimeField(blank=True, verbose_name='date posted')),
            ],
        ),
    ]
